// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class AndroidController
{
        public const string leaderboard_top_player = "CgkI-6upgdEeEAIQBg"; // <GPGSID>
        public const string achievement_endboss = "CgkI-6upgdEeEAIQAw"; // <GPGSID>
        public const string achievement_endless_space = "CgkI-6upgdEeEAIQBQ"; // <GPGSID>
        public const string achievement_spaceshopper = "CgkI-6upgdEeEAIQAQ"; // <GPGSID>
        public const string achievement_master_of_the_universe = "CgkI-6upgdEeEAIQCQ"; // <GPGSID>
        public const string achievement_spacinator = "CgkI-6upgdEeEAIQCA"; // <GPGSID>
        public const string achievement_die = "CgkI-6upgdEeEAIQBA"; // <GPGSID>
        public const string achievement_skiller = "CgkI-6upgdEeEAIQAg"; // <GPGSID>
        public const string achievement_crusher = "CgkI-6upgdEeEAIQBw"; // <GPGSID>

}

